version: "3"

services:
  db:
    container_name: db_shorten
    image: postgres:latest
    environment:
      - POSTGRES_DB=dev
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=dev
    ports:
      - "5432:5432"
